# Generated by Django 3.2.5 on 2021-08-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultprocessing', '0002_alter_crowdmessage_then_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crowdmessage',
            table='crowdmessage',
        ),
    ]
